### ISSUE TITLE
Can you provide your pretrained model?

### ISSUE THREAD

**Issue by Seagullflysxt** [Terascale-All-sensing-Research-Studio/DeepJoin#1]
Hi,thanks for your great work:)
Can you provide your pretrained model on mug in example_files->pts.npz?It looks missing in the uploaded files.
And in the fracturing directory, I tried to go through step 1-warterproofing,I use your scripts, but it said 
```shell
TypeError: rebalance_split_train_test_val() missing 1 required positional argument: 'train_val_test_ratio
```
I found it int the process.py ,in line 121,it said:
```shell
# This should have a passable ratio but I dont have time
        id_train_list, id_val_list, id_test_list = utils.rebalance_split_train_test_val(
            id_train_list, id_test_list
        )
```
I set the ratio to be [0.6, 0.2, 0.2],is it a proper ratio?

Could you please tell me what should I do with it? 
Great thanks to you :)

**Comment by nikwl** [comment]
Thanks for your interest in our work!

We do provide weights for the trained mugs class, they can be found in: 
https://github.com/Terascale-All-sensing-Research-Studio/DeepJoin/tree/main/deepjoin/experiments/mugs
If you run the [Quickstart Inference](https://github.com/Terascale-All-sensing-Research-Studio/DeepJoin#quickstart-inference), the weights will be loaded and used to predict a restoration for an input object. 

You're right, it looks like `process.py` is missing a positional argument, looks like I need to fix that. We use `train_val_test_ratio=[0.7, 0.1, 0.2]`.
